### ISSUE TITLE
Set up Project In flutter

### ISSUE THREAD

**Issue by abhishekpatelmc** [abhishekpatelmc/food-Analyzer-App#1]
- Create a flutter project to get started.

**Comment by pratishthaa** [comment]
So, one or everyone is supposed to create the basic Flutter application for this?

**Comment by abhishekpatelmc** [comment]
####  One is enough, to get started with the project.
- create a flutter environment 
- push the code to GitHub 
- No need to develop any pages 
- Creating pages can be raised as a new issue

**Comment by pratishthaa** [comment]
Can I be assigned then?

**Comment by abhishekpatelmc** [comment]
Yes, you can create a environment so that everyone can work on it
